import "./globals.css";
import Navbar from "@/components/common/navbar/Navbar";
// Removed import of @studio-freight/react-lenis due to error
// Removed import of next/font/google due to error

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning={true}>
        {/* Removed <ReactLenis root> due to error */}
        <header>
          <Navbar />
        </header>
        {children}
        {/* End of removed <ReactLenis root> */}
      </body>
    </html>
  );
}
